import * as THREE from "three";

/**
 * Three.js mirrors of the CSS theme tokens in app/globals.css.
 * Use these for canvas-side color constants so the 3D palette stays in sync
 * with the UI and can be updated from one place.
 */
export const THEME = {
  // CSS-mirror tokens
  space: new THREE.Color("#04060f"),
  space2: new THREE.Color("#0b1226"),
  ink: new THREE.Color("#e8eefc"),
  inkDim: new THREE.Color("#8ea3c4"),
  ocean: new THREE.Color("#1656d6"),
  oceanLit: new THREE.Color("#3b82f6"),
  cyan: new THREE.Color("#7dd3fc"),
  gold: new THREE.Color("#f0c75e"),
  goldDeep: new THREE.Color("#c9a13b"),
  danger: new THREE.Color("#e0563f"),
  dangerBright: new THREE.Color("#ff7a62"),
  success: new THREE.Color("#4ade80"),

  // 3D palette tokens
  white: new THREE.Color("#ffffff"),
  inkLight: new THREE.Color("#f5f7ff"),
  coin: new THREE.Color("#ffd23d"),
  dmgKill: new THREE.Color("#ff6b6b"),
  siteLabel: new THREE.Color("#ffd97a"),
  labelOutline: new THREE.Color("#050814"),
  flameA: new THREE.Color("#ffe89e"),
  flameB: new THREE.Color("#ff8c3d"),
  flameC: new THREE.Color("#ff3d3d"),
  arcCore: new THREE.Color("#f2fbff"),
  arcGlow: new THREE.Color("#4f9dff"),
  bossMenace: new THREE.Color("#8b1020"),
  crimson: new THREE.Color("#ff4d4d"),
  amber: new THREE.Color("#f59e0b"),
  bossFlash: new THREE.Color("#ffae70"),
  warnLate: new THREE.Color("#ff1f1f"),
  warnEarly: new THREE.Color("#ff9f1c"),
  tempest: new THREE.Color("#ff4d3d"),
  shuriken: new THREE.Color("#7db2ff"),
  steel: new THREE.Color("#c7d0e2"),
  coinDisc: new THREE.Color("#0b0b0d"),
  coinRim: new THREE.Color("#23232e"),
  pulseCore: new THREE.Color("#eafeff"),
  pulseGlow: new THREE.Color("#22d3ee"),
  boomCore: new THREE.Color("#fffbe8"),
  captureCore: new THREE.Color("#fff6dc"),
  bladeSteel: new THREE.Color("#e8eef6"),
  bladeEmissive: new THREE.Color("#b9c8dc"),
  katanaBlade: new THREE.Color("#dbe6f2"),
  grip: new THREE.Color("#141c2c"),
  slash: new THREE.Color("#cfdcec"),
  halo: new THREE.Color("#ffb02e"),
  haloFill: new THREE.Color("#ff7a1a"),
  smoke: new THREE.Color("#39404f"),
  glitchBack: new THREE.Color("#100902"),
  glitchAmberBright: new THREE.Color("#fde047"),
  glitchAmber: new THREE.Color("#fbbf24"),
  glitchPink: new THREE.Color("#f472b6"),
  gweiBack: new THREE.Color("#1a0c05"),
  gweiText: new THREE.Color("#ffb74a"),
  gweiTextDim: new THREE.Color("#ff9a3d"),
  bugAbdomen: new THREE.Color("#1c1206"),
  bugThorax: new THREE.Color("#33260c"),
  bugHead: new THREE.Color("#171004"),
  bugMandibleEmissive: new THREE.Color("#b45309"),
  bugLeg: new THREE.Color("#3d2e10"),
  bugLegDark: new THREE.Color("#332609"),
  wispAmber: new THREE.Color("#f5a94b"),
  wispEmber: new THREE.Color("#d97706"),
  wispCore: new THREE.Color("#fff3c4"),
  wispCoreEmissive: new THREE.Color("#ffe08a"),
  wispEyes: new THREE.Color("#1a0c05"),
  rugCrimson: new THREE.Color("#8b1f2f"),
  rugCrimsonDark: new THREE.Color("#5f1420"),
  goldEmissive: new THREE.Color("#c9921e"),
  hull: new THREE.Color("#2a3a63"),
  hullDark: new THREE.Color("#141c33"),
  hullEmissive: new THREE.Color("#2a4080"),
  mask: new THREE.Color("#0c0f16"),
  theoChrome: new THREE.Color("#9aa3b2"),
  theoBlue: new THREE.Color("#1e4fd8"),
  theoEye: new THREE.Color("#4f7dff"),
  jackHair: new THREE.Color("#4a2f15"),
  jackHair2: new THREE.Color("#553a1d"),
  jackShirt: new THREE.Color("#f2f2f2"),
  jackShirt2: new THREE.Color("#e9e9e9"),
  cyanHot: new THREE.Color("#67e8f9"),
  dmgOutline: new THREE.Color("#0b0e18"),
} as const;

/** Hex strings for places that still need a string (canvas text, particle colors). */
export const HEX = {
  // CSS-mirror tokens
  space: "#04060f",
  space2: "#0b1226",
  ink: "#e8eefc",
  inkDim: "#8ea3c4",
  ocean: "#1656d6",
  oceanLit: "#3b82f6",
  cyan: "#7dd3fc",
  gold: "#f0c75e",
  goldDeep: "#c9a13b",
  danger: "#e0563f",
  dangerBright: "#ff7a62",
  success: "#4ade80",

  // 3D palette tokens
  white: "#ffffff",
  inkLight: "#f5f7ff",
  coin: "#ffd23d",
  dmgKill: "#ff6b6b",
  siteLabel: "#ffd97a",
  labelOutline: "#050814",
  flameA: "#ffe89e",
  flameB: "#ff8c3d",
  flameC: "#ff3d3d",
  arcCore: "#f2fbff",
  arcGlow: "#4f9dff",
  bossMenace: "#8b1020",
  crimson: "#ff4d4d",
  amber: "#f59e0b",
  bossFlash: "#ffae70",
  warnLate: "#ff1f1f",
  warnEarly: "#ff9f1c",
  tempest: "#ff4d3d",
  shuriken: "#7db2ff",
  steel: "#c7d0e2",
  coinDisc: "#0b0b0d",
  coinRim: "#23232e",
  pulseCore: "#eafeff",
  pulseGlow: "#22d3ee",
  boomCore: "#fffbe8",
  captureCore: "#fff6dc",
  bladeSteel: "#e8eef6",
  bladeEmissive: "#b9c8dc",
  katanaBlade: "#dbe6f2",
  grip: "#141c2c",
  slash: "#cfdcec",
  halo: "#ffb02e",
  haloFill: "#ff7a1a",
  smoke: "#39404f",
  glitchBack: "#100902",
  glitchAmberBright: "#fde047",
  glitchAmber: "#fbbf24",
  glitchPink: "#f472b6",
  gweiBack: "#1a0c05",
  gweiText: "#ffb74a",
  gweiTextDim: "#ff9a3d",
  bugAbdomen: "#1c1206",
  bugThorax: "#33260c",
  bugHead: "#171004",
  bugMandibleEmissive: "#b45309",
  bugLeg: "#3d2e10",
  bugLegDark: "#332609",
  wispAmber: "#f5a94b",
  wispEmber: "#d97706",
  wispCore: "#fff3c4",
  wispCoreEmissive: "#ffe08a",
  wispEyes: "#1a0c05",
  rugCrimson: "#8b1f2f",
  rugCrimsonDark: "#5f1420",
  goldEmissive: "#c9921e",
  hull: "#2a3a63",
  hullDark: "#141c33",
  hullEmissive: "#2a4080",
  mask: "#0c0f16",
  theoChrome: "#9aa3b2",
  theoBlue: "#1e4fd8",
  theoEye: "#4f7dff",
  jackHair: "#4a2f15",
  jackHair2: "#553a1d",
  jackShirt: "#f2f2f2",
  jackShirt2: "#e9e9e9",
  cyanHot: "#67e8f9",
  dmgOutline: "#0b0e18",
} as const;

/** Convert a hex string to an `rgba(...)` string for canvas 2D APIs. */
export function rgba(hex: string, alpha: number): string {
  const c = new THREE.Color(hex);
  return `rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${alpha})`;
}
